-- Q2: ids de la SO draft y del partner Odoo

ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "odooPartnerId" INTEGER;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "odooContactId" INTEGER;

ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooSaleId" INTEGER;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooSaleName" TEXT;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooState" TEXT;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooInvoiceStatus" TEXT;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooAmountUntaxed" DECIMAL(16,2);
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooAmountTax" DECIMAL(16,2);
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooAmountTotal" DECIMAL(16,2);
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooUrl" TEXT;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "odooPartnerId" INTEGER;

CREATE INDEX IF NOT EXISTS "Quote_odooSaleId_idx" ON "Quote"("odooSaleId");
