-- Q1: RUC SUNAT para cotizar (cuenta puede nacer sin RUC)

ALTER TABLE "Customer" ALTER COLUMN "rucDni" SET DEFAULT '';
ALTER TABLE "Customer" ALTER COLUMN "companyName" SET DEFAULT '';
ALTER TABLE "Customer" ALTER COLUMN "phone" SET DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "street" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "district" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "province" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "sunatState" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "sunatCondition" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "rucValidatedAt" TIMESTAMP(3);
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "rucLookupAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "rucLookupLockedUntil" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Customer_rucDni_idx" ON "Customer"("rucDni");
